In [ ]:
import pandas as pd
from sklearn.ensemble import RandomForestClassifier

In [5]:
df = pd.read_csv('../data/balanced.csv')
df.head()

,sex,is_employed,income,num_vehicles,age,state_of_res,gas_usage,rooms,marital_status_Divorced/Separated,marital_status_Married,marital_status_Never married,marital_status_Widowed,housing_type_Homeowner free and clear,housing_type_Homeowner with mortgage/loan,housing_type_Occupied with no rent,housing_type_Rented,health_ins
0,1,1,-0.35,0.0,0.04,0,2.67,3,0,0,1,0,1,0,0,0,1
1,0,0,-0.33,0.0,0.78,0,-0.61,6,1,0,0,0,0,0,0,1,1
2,0,1,-0.37,2.0,0.13,0,-0.02,3,0,0,1,0,0,1,0,0,1
3,0,0,-0.08,1.0,0.92,0,1.25,2,0,0,0,1,1,0,0,0,1
4,1,1,-0.06,2.0,0.59,0,-0.61,2,1,0,0,0,0,0,0,1,1

In [6]:
X = df.drop('health_ins', axis=1)
y = df['health_ins']
X.shape, y.shape

((129645, 16), (129645,))